export const INIT_ALL_QUERIES = 'INIT_ALL_QUERIES';
export const FETCH_QUERIES_FAILED = 'FETCH_QUERIES_FAILED';
export const SET_QUERIES = 'SET_QUERIES';
export const QUERY_SELECTED = 'QUERY_SELECTED';

export const INIT_ALL_STATIONARY_POINTS = 'INIT_ALL_STATIONARY_POINTS';
export const FETCH_STATIONARY_POINTS_FAILED = 'FETCH_STATIONARY_POINTS_FAILED';
export const SET_STATIONARY_POINTS = 'SET_STATIONARY_POINTS';
export const STATIONARY_POINT_SELECTED = 'STATIONARY_POINT_SELECTED';

export const INIT_ADMIN_LOGIN = 'INIT_ADMIN_LOGIN';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const INIT_ALL_USERS_LIST='INIT_ALL_USERS_LIST';
export const FETCH_USERS_LIST_FAILED='FETCH_USERS_LIST_FAILED';
export const SET_USERS_LIST='SET_USERS_LIST';