export const INIT_ALL_QUERIES = 'INIT_ALL_QUERIES';
export const FETCH_QUERIES_FAILED = 'FETCH_QUERIES_FAILED';
export const SET_QUERIES = 'SET_QUERIES';
export const QUERY_SELECTED = 'QUERY_SELECTED';

export const INIT_ALL_STATIONARY_POINTS = 'INIT_ALL_STATIONARY_POINTS';
export const FETCH_STATIONARY_POINTS_FAILED = 'FETCH_STATIONARY_POINTS_FAILED';
export const SET_STATIONARY_POINTS = 'SET_STATIONARY_POINTS';
export const STATIONARY_POINT_SELECTED = 'STATIONARY_POINT_SELECTED';
export const DELETE_STATIONARY_POINT = 'DELETE_STATIONARY_POINT';

export const INIT_ALL_PLAYLISTS = 'INIT_ALL_PLAYLISTS';
export const FETCH_PLAYLISTS_FAILED = 'FETCH_PLAYLISTS_FAILED';
export const SET_PLAYLISTS = 'SET_PLAYLISTS';
export const PLAYLIST_SELECTED = 'PLAYLIST_SELECTED';
export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS';
export const CREATE_PLAYLIST_FAILED = 'CREATE_PLAYLIST_FAILED';
export const UPDATE_PLAYLIST_SUCCESS = 'UPDATE_PLAYLIST_SUCCESS';
export const UPDATE_PLAYLIST_FAILED = 'UPDATE_PLAYLIST_FAILED';
export const FETCH_ONE_PLAYLIST_SUCCESS = 'FETCH_ONE_PLAYLIST_SUCCESS';
export const FETCH_ONE_PLAYLIST_FAILED = 'FETCH_ONE_PLAYLIST_FAILED';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';


export const INIT_ADMIN_LOGIN = 'INIT_ADMIN_LOGIN';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const INIT_ALL_USERS_LIST = 'INIT_ALL_USERS_LIST';
export const FETCH_USERS_LIST_FAILED = 'FETCH_USERS_LIST_FAILED';
export const SET_USERS_LIST = 'SET_USERS_LIST';